module.exports = {
  content: [
    './resources/**/*.blade.php',
    './resources/**/*.js',
    './resources/**/*.ts',
    './resources/**/*.vue',
    './app/**/*.php',
    './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
    './storage/framework/views/*.php',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    { pattern: /^bg-/ },
    { pattern: /^text-/ },
    { pattern: /^w-/ },
    { pattern: /^h-/ },
    { pattern: /^p-/ },
    { pattern: /^px-/ },
    { pattern: /^py-/ },
    { pattern: /^rounded-/ },
    { pattern: /^shadow-/ },
    { pattern: /^gap-/ },
    { pattern: /^grid-/ },
    { pattern: /^flex-/ },
    { pattern: /^items-/ },
    { pattern: /^justify-/ },
    { pattern: /^ring-/ },
    { pattern: /^opacity-/ },
    { pattern: /^container$/ },
  ],
};
